package vista;

import control.ControlPedidos;
import dominio.Ingrediente;
import java.awt.Dimension;
import java.awt.Point;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel Vega
 */
public class DlgPersonalizarProducto extends javax.swing.JDialog {
    private ControlPedidos c = ControlPedidos.getInstance();
    private List<Ingrediente> ingredientes;
    private int fila;
    
    public DlgPersonalizarProducto(java.awt.Frame parent, boolean modal, List<Ingrediente> ingredientes) {
        super(parent, modal);
        this.ingredientes = ingredientes;
        initComponents();
        
        for (Ingrediente ingrediente : this.ingredientes) {
            if(ingrediente.getNombre().equalsIgnoreCase("masa")) {
            } else if(ingrediente.getNombre().equalsIgnoreCase("pure de tomate")) {
            } else if(ingrediente.getNombre().equalsIgnoreCase("queso")) {
            } else if(ingrediente.getCantidad() == 0) {
            } else {
                JCheckBox checkBox = new JCheckBox(ingrediente.getNombre());
                this.panelIngredientes.add(checkBox);
            }
        }
        
        this.panelIngredientes.revalidate();
        this.panelIngredientes.repaint();
        this.panelIngredientes.setVisible(true);
        
        this.centraCuadroDialogo(parent);
    }
    
    private void centraCuadroDialogo(java.awt.Frame parent){
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();
        
        Dimension dlgSize = getPreferredSize();
        
        setLocation( (frameSize.width - dlgSize.width) / 2 + loc.x,
                     (frameSize.height - dlgSize.height) / 2 + loc.y);
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelIngredientes = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personalizar Producto");
        setBackground(new java.awt.Color(220, 230, 250));
        setResizable(false);

        jLabel1.setText("Ingredientes a agregar");

        panelIngredientes.setLayout(new java.awt.GridLayout(ingredientes.size(), 0));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 455, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int nIngredientesSelec = 0;
        StringBuilder extras = new StringBuilder("(Extras: ");
        
        for (int i = 0; i < this.panelIngredientes.getComponentCount(); i++) {
            if(this.panelIngredientes.getComponent(i) instanceof JCheckBox) {
                JCheckBox check = (JCheckBox) this.panelIngredientes.getComponent(i);
                if(check.isSelected()) {
                    nIngredientesSelec += 1;
                    extras.append(check.getText()).append(", ");
                }
            }
        }
        
        if(nIngredientesSelec > 0) {
            extras.setLength(extras.length() - 2);
        } else {
            JOptionPane.showMessageDialog(this, "No has seleccionado ni una opción", "No hay selecciones", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        extras.append(")");
        
        JOptionPane.showMessageDialog(this, "Extras agregados correctamente", "Extras agregados!!", JOptionPane.PLAIN_MESSAGE);
        
        c.agregarIngredientes(nIngredientesSelec, extras.toString(), fila);
        c.actualizarRealizarPedido();
        
        dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelIngredientes;
    // End of variables declaration//GEN-END:variables
}
